### ISSUE TITLE
unknown "private keys" import

### ISSUE THREAD

**Issue by enricocovili** [LolloBorghi/temperatures#1]
[Referring to this line of code](https://github.com/LolloBorghi/temperatures/blob/510b83301a8f1c28eba2dcce96389b4d87d5c1b5/py_script/remote_ctrl.py#L3)

What is "private_keys"? Is it a python module installed from PyPI or a simple file located somewhere else in your PC?
I am asking this as i don't see any .gitignore file that contains reference to some config files.

Kind regards,
Enrico

**Comment by velcom-tu-brolalla** [comment]
I dink iu shuld apload privat kis.py hiere on github bcos i donnt hav a influxdb acount maiself and i wuld laik to use iuors

**Comment by metafrollo** [comment]
Thank you for your issue report.
I fixed the problem in the last commit, now it **should** be fine.
