### ISSUE TITLE
Mising bash suport

### ISSUE THREAD

**Issue by velcom-tu-brolalla** [LolloBorghi/temperatures#2]
I tink dis is a rily gud proiect but it sims to be mising bash suport, i rly ate piton and i wuld laik to sii it writen in besh bicos piton bad.
also i tink thaat u shuld stop writing C and use C 2 (C++) bicos it is beter

**Comment by metafrollo** [comment]
I'm sorry, but this repository is never going to support bash.
Thank you for your report.
